# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

jobs:
  build:
    macos:
      xcode: 11.0.0 # Specify the Xcode version to use

    steps:
      - run:
          name: The First Step
          command: |
            brew update
            bundle install
      - run:
          name: Code Has Arrived
          command: |
            bundle exec fastlane test
